### ISSUE TITLE
/path/to/lgsm/folder does not exist or not readable?

### ISSUE THREAD

**Issue by eikichi87** [seancallaway/dodscp#12]
Hi,

I'm getting this message after I try to set my lgsm folder path:
**/path/to/lgsm/server/folder does not exist or is not readable, Try again.**

What can I do to solve this?
I run your script as root, and the lgsm folder has a normal user.
Thanks.

**Comment by seancallaway** [comment]
You're actually supposed to be setting the full path to the script there, not the folder containing the script. The check is failing because you're either not pointing at a file (which makes sense based on the pseudo-path you provided) or it's not readable.

**Comment by seancallaway** [comment]
Did this solve your problem?

**Comment by seancallaway** [comment]
Going to go ahead and close this one then.
